// Code generated by MockGen. DO NOT EDIT.
// Source: ../repository/interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/guntoroyk/cake-store-api/entity"
)

// MockCakeRepoItf is a mock of CakeRepoItf interface.
type MockCakeRepoItf struct {
	ctrl     *gomock.Controller
	recorder *MockCakeRepoItfMockRecorder
}

// MockCakeRepoItfMockRecorder is the mock recorder for MockCakeRepoItf.
type MockCakeRepoItfMockRecorder struct {
	mock *MockCakeRepoItf
}

// NewMockCakeRepoItf creates a new mock instance.
func NewMockCakeRepoItf(ctrl *gomock.Controller) *MockCakeRepoItf {
	mock := &MockCakeRepoItf{ctrl: ctrl}
	mock.recorder = &MockCakeRepoItfMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCakeRepoItf) EXPECT() *MockCakeRepoItfMockRecorder {
	return m.recorder
}

// CreateCake mocks base method.
func (m *MockCakeRepoItf) CreateCake(cake *entity.Cake) (*entity.Cake, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCake", cake)
	ret0, _ := ret[0].(*entity.Cake)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCake indicates an expected call of CreateCake.
func (mr *MockCakeRepoItfMockRecorder) CreateCake(cake interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCake", reflect.TypeOf((*MockCakeRepoItf)(nil).CreateCake), cake)
}

// DeleteCake mocks base method.
func (m *MockCakeRepoItf) DeleteCake(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCake", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCake indicates an expected call of DeleteCake.
func (mr *MockCakeRepoItfMockRecorder) DeleteCake(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCake", reflect.TypeOf((*MockCakeRepoItf)(nil).DeleteCake), id)
}

// GetCake mocks base method.
func (m *MockCakeRepoItf) GetCake(id int) (*entity.Cake, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCake", id)
	ret0, _ := ret[0].(*entity.Cake)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCake indicates an expected call of GetCake.
func (mr *MockCakeRepoItfMockRecorder) GetCake(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCake", reflect.TypeOf((*MockCakeRepoItf)(nil).GetCake), id)
}

// GetCakes mocks base method.
func (m *MockCakeRepoItf) GetCakes() ([]*entity.Cake, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCakes")
	ret0, _ := ret[0].([]*entity.Cake)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCakes indicates an expected call of GetCakes.
func (mr *MockCakeRepoItfMockRecorder) GetCakes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCakes", reflect.TypeOf((*MockCakeRepoItf)(nil).GetCakes))
}

// UpdateCake mocks base method.
func (m *MockCakeRepoItf) UpdateCake(cake *entity.Cake) (*entity.Cake, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCake", cake)
	ret0, _ := ret[0].(*entity.Cake)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCake indicates an expected call of UpdateCake.
func (mr *MockCakeRepoItfMockRecorder) UpdateCake(cake interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCake", reflect.TypeOf((*MockCakeRepoItf)(nil).UpdateCake), cake)
}
